# Institution-Specific Configuration

institution:
  name: "BCFHD"
  description: "humanitarian organization"
  website: "https://www.bcfhd.org/"
  contact_email: "bena@bcfhd.org"
  timezone: "Arabia Standard Time"
  
  # Institution-specific settings
  departments:
    - "Computer Science"
    - "Engineering" 
    - "Mathematics"
  
  academic_calendar:
    semester_system: true
    current_semester: "Fall 2024"

# Custom AI model preferences
ai_models:
  primary_model: "deepseek/deepseek-prover-v2:free"
  temperature: 0.5
