# Local Development Configuration
# This file should be in .gitignore

# Development settings
logging:
  level: "DEBUG"
  console_output: true

# Local API settings
api:
  cors_origins: ["http://localhost:3000", "http://127.0.0.1:3000"]

# Development cache settings
cache:
  ttl: 3600  # Shorter cache for development
  max_size: 1000

# Test AI model (cheaper for development)
ai_models:
  primary_model: "deepseek/deepseek-prover-v2:free"
  timeout: 20
